themes/theme-default/src/client/styles/layout.scss, themes/theme-default/src/client/styles/normalize.scss
…(vuepress#1363)
The heading anchors have `aria-hidden` attributes but are still focusable via keyboard navigation.  There was a bit of discussion around this already in the [`markdown-it-anchor` repo](https://github.com/valeriangalliat/markdown-it-anchor/issues/82) and you can address this by just using the `headerLink` render function instead of the `ariaHidden` render function since it wraps the entire header in an anchor.
This PR is the `theme-default` style updates for the markup changes from [PR #1452](https://github.com/vuepress/vuepress-next/pull/1452) in `vuepress-next`.
This fixes #1363 
Hover
Hover
Hover
=> feat(theme-default): sync anchor permalink function updates for better a11y

themes/theme-default/src/client/components/global/CodeGroup.ts, themes/theme-default/src/client/components/global/CodeGroupItem.vue, themes/theme-default/src/client/styles/code-group.scss, themes/theme-default/src/client/styles/vars.scss
While doing some accessibility testing on [my site](https://datagridvue.com) written in the RC release of Vuepress 2 I came across some accessibility issues with the code group and code group item components.
I have been testing with the latest version of the [axe chrome extension](https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?utm_source=deque.com&utm_medium=referral&utm_campaign=axe_hero).
It reported on the code block item component that `Elements must only use supported ARIA attributes`.  
https://dequeuniversity.com/rules/axe/4.8/aria-allowed-attr?application=AxeChrome
The code group item component renders the [`aria-selected`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected) attribute which …
=> fix(theme-default): code group accessibility

docs/plugins/sitemap/config.md, docs/plugins/sitemap/guide.md, docs/zh/plugins/sitemap/config.md, docs/zh/plugins/sitemap/guide.md, e2e/docs/.vuepress/config.ts, plugins/plugin-sitemap/src/node/getInfo.ts, plugins/plugin-sitemap/src/typings/options.ts
BREAKING CHANGE: `excludeUrls` is renamed to `excludePaths`
=> feat(plugin-sitemap): rename excludeUrls to excludePaths

plugins/plugin-baidu-analytics/src/client/config.ts
=> fix(plugin-baidu-analytics): fix client-side error

plugins/plugin-git/src/node/utils/getCreatedTime.ts
The previous **createdTime** is imprecise, add `--follow` parameter to the `git log` command so that it *continues listing the history of a file beyond renames*
=> fix(plugin-git): add the --follow parameter to the git log command

plugins/plugin-comment/src/client/components/ArtalkComment.ts, plugins/plugin-comment/src/client/components/CommentService.ts, plugins/plugin-comment/src/client/components/GiscusComment.ts, plugins/plugin-comment/src/client/components/TwikooComment.ts, plugins/plugin-comment/src/client/components/WalineComment.ts, plugins/plugin-comment/src/client/helpers/comment.ts, plugins/plugin-comment/src/client/pageview/artalk.ts, plugins/plugin-comment/src/client/pageview/waline.ts, plugins/plugin-docsearch/src/client/helpers/docsearch.ts, plugins/plugin-photo-swipe/src/client/composables/usePhotoSwipe.ts, plugins/plugin-photo-swipe/src/client/helpers/photo-swipe.ts
#111 
Adjust the `defineXXXConfig(options)` function parameters exported by some plugins, updating the type of the `options` parameter to `MaybeRefOrGetter<XXX>`. This allows third parties to have more flexibility in controlling the behavior of the plugins when using them.
**plugin-photo-swipe**：
```diff
- export const definePhotoSwipeConfig = (options: PhotoSwipeOptions)
+ export const definePhotoSwipeConfig = (options: MaybeRefOrGetter<PhotoSwipeOptions>)
```
**plugin-docsearch**
```diff
- export const defineDocSearchConfig = (options: DocSearchClientOptions)
+ export const defineDocSearchConfig = (options: MaybeRefOrGetter<DocSearchClientOptions>)
```
**plugin-comment**
I'm not sure if it's necessary to modify the 'defineXXXConfig' exported by the comment plugin, so I haven't made any …
=> `defineXXXConfig` support `MaybeRefOrGetter` options

plugins/plugin-prismjs/src/node/markdown/highlightPlugin.ts, plugins/plugin-prismjs/src/node/markdown/lineNumbersPlugin.ts, plugins/plugin-prismjs/src/node/prismjsPlugin.ts, plugins/plugin-prismjs/src/node/types.ts, plugins/plugin-prismjs/tests/prismjs-preWrapper.spec.ts, plugins/plugin-shiki/src/node/index.ts, plugins/plugin-shiki/src/node/markdown/lineNumberPlugin.ts, plugins/plugin-shiki/src/node/markdown/preWrapperPlugin.ts, plugins/plugin-shiki/src/node/resolveHighlight.ts, plugins/plugin-shiki/src/node/shikiPlugin.ts, plugins/plugin-shiki/src/node/transformers/getTransformers.ts, plugins/plugin-shiki/src/node/transformers/vuepressTransformers.ts, plugins/plugin-shiki/src/node/types.ts, plugins/plugin-shiki/tests/shiki-preWrapper.spec.ts
improve types.
- `@vuepress/plugin-prismjs`
- `@vuepress/plugin-shiki`
=> feat: improve types

docs/plugins/copy-code.md, docs/zh/plugins/copy-code.md, plugins/plugin-copy-code/src/client/composables/useCopyCode.ts, plugins/plugin-copy-code/src/client/styles/copied-button.svg, plugins/plugin-copy-code/src/client/styles/copy-button.svg, plugins/plugin-copy-code/src/client/styles/copy-code.css, plugins/plugin-copy-code/src/client/styles/copy-code.scss, plugins/plugin-copy-code/src/client/styles/vars.css, plugins/plugin-copy-code/src/client/utils/index.ts, plugins/plugin-copy-code/src/client/utils/isMobile.ts, plugins/plugin-copy-code/src/node/copyCodePlugin.ts, plugins/plugin-copy-code/src/node/options.ts, plugins/plugin-copy-code/tsconfig.build.json
- Optimize the `plugin-copy-code` code
- Add new options `ignoreNodes` and `transform`
=> feat(plugin-copy-code): add `ignoreSelector` and `transform` options

plugins/plugin-prismjs/src/node/markdown/preWrapperPlugin.ts, plugins/plugin-shiki/src/node/markdown/preWrapperPlugin.ts
The preWrapper plugin should only wrap a `<div>` element when the fence result is a `<pre>` element
=> fix: fix preWrapper plugin

themes/theme-default/src/client/styles/code.scss
The height of `.line-number` should be calculated based on the `font-size` and `line-height` of `.line-numbers`, rather than being directly set to `{line-height}em`, as this could lead to rendering issues.
```diff
.line-number {
...
-  height: #{$line-height}em;
}
```
=> fix(theme-default): code block line number misalignment in Safari

.vscode/settings.json, plugins/markdown/plugin-shiki/package.json, plugins/markdown/plugin-shiki/src/node/resolveHighlight.ts, plugins/markdown/plugin-shiki/src/node/utils.ts, plugins/markdown/plugin-shiki/tsconfig.build.json, pnpm-lock.yaml
The original warnings does not have source, and a bit ugly:
=> chore(plugin-shiki): improve shiki logger

plugins/development/plugin-rtl/src/node/rtlPlugin.ts
There was a spelling mistake in the rtlPlugin. When I attempted to retrieve the package, it returned an error saying that the package could not be found.
=> fix: correct spelling in RTL implementation

docs/plugins/tools/redirect.md, docs/zh/plugins/tools/redirect.md, e2e/docs/.vuepress/styles/default-palette.scss, e2e/tests/plugin-sass-palette/sass-palette.spec.ts, plugins/tools/plugin-redirect/src/client/components/RedirectModal.ts, plugins/tools/plugin-redirect/src/client/styles/redirect-modal.scss, plugins/tools/plugin-redirect/src/node/locales.ts, plugins/tools/plugin-redirect/src/shared/locales.ts
=> feat(plugin-redirect): add remember my choice, close #253

plugins/markdown/plugin-markdown-hint/src/client/styles/hint.scss, plugins/markdown/plugin-markdown-hint/src/client/styles/vars.css, themes/theme-default/src/client/styles/plugins.scss
The hint container is a bit large in the context around it, so we shrink it:
**Before**
**After**
Before:
After:
=> feat(plugin-markdown-hint): improve hint container outlook

docs/plugins/markdown/revealjs/README.md, docs/zh/plugins/markdown/revealjs/README.md
Bug fix: Changed 'prismjs' to 'revealjs'
Modify the error in [Document](https://ecosystem.vuejs.press/plugins/markdown/revealjs/#usage), `prismjs` should be `revealjs`   
**Before**
**After**
=> fix(README.md): Changed 'prismjs' to 'revealjs'

e2e/docs/.vuepress/components/ArticleList.vue, e2e/docs/.vuepress/layouts/Category.vue, e2e/docs/.vuepress/layouts/Tag.vue, e2e/docs/.vuepress/layouts/Timeline.vue, tools/create-vuepress/template/blog/.vuepress/components/ArticleList.vue, tools/create-vuepress/template/blog/.vuepress/layouts/Category.vue, tools/create-vuepress/template/blog/.vuepress/layouts/Tag.vue, tools/create-vuepress/template/blog/.vuepress/layouts/Timeline.vue
fix content overlap by adjusting padding in Category, Tag, Timeline and ArticleList components
This PR fixes the issue where content in blog components (Category, Tag, Timeline, and ArticleList) is partially hidden behind the navbar. The solution adds proper padding using the existing navbar height CSS variable.
```
e2e/docs/vuepress/layouts/Category.vue
e2e/docs/vuepress/layouts/Tag.vue
e2e/docs/vuepress/layouts/Timeline.vue
e2e/docs/vuepress/layouts/ArticleList.vue
tools/create-vuepress/template/blog/.vuepress/layouts/Category.vue
tools/create-vuepress/template/blog/.vuepress/layouts/Tag.vue
tools/create-vuepress/template/blog/.vuepress/layouts/Timeline.vue
tools/create-vuepress/template/blog/.vuepress/layouts/ArticleList.vue
```
```diff
// Category.vue, Tag.vue
.category-wrapper, …
```
=> fix(theme-blog): prevent navbar overlap in blog components

tools/helper/src/client/styles/sr-only.scss
`clip` has been [deprecated](https://developer.mozilla.org/en-US/docs/Web/CSS/clip), and `rect (0, 0, 0, 0)` should be `rect(0 0 0 0)`
=> fix(helper): `.sr-only` clip

docs/plugins/blog/blog/guide.md
This was causing an error: "useBlogCategory" is not exported by "node_modules/@vuepress/plugin-blog/lib/node/index.js"
=> Fix import for @vuepress/plugin-blog/client

docs/themes/default/extending.md, docs/zh/themes/default/extending.md, themes/theme-default/src/client/components/VPAutoLink.vue, themes/theme-default/src/client/components/VPHomeHero.vue, themes/theme-default/src/client/components/VPNavbarDropdown.vue, themes/theme-default/src/client/components/VPNavbarItems.vue, themes/theme-default/src/client/components/VPPageMeta.vue, themes/theme-default/src/client/components/VPPageNav.vue, themes/theme-default/src/client/components/VPSidebarItem.vue, themes/theme-default/src/client/composables/useEditLink.ts, themes/theme-default/src/client/composables/useNavbarConfig.ts, themes/theme-default/src/client/composables/useNavbarRepo.ts, themes/theme-default/src/client/composables/useRelatedLinks.ts, themes/theme-default/src/client/composables/useSidebarItems.ts, themes/theme-default/src/client/utils/index.ts, themes/theme-default/src/client/utils/isActiveSidebarItem.ts, themes/theme-default/src/client/utils/resolveAutoLink.ts, themes/theme-default/src/client/utils/resolveEditLink.ts, themes/theme-default/src/node/defaultTheme.ts, themes/theme-default/tsconfig.build.json, tsconfig.json
This PR introduce:
- A new VPAutoLink component to be overrided
- Alias for all utils functions
This allows people to customize default theme more easily, e.g.: adding icons
=> feat(theme-default): improve theme extending

tools/highlighter-helper/src/client/styles/collapsed-lines.scss
Impoves hover state
- adds a hover state when the lines are expanded
- use highlight bg to mark the hover state. This solves the problem hover state is unrecognizable when code bg is black
=> feat(highlighter-helper): improve collapsed lines styles

docs/plugins/tools/redirect.md, docs/zh/plugins/tools/redirect.md, plugins/tools/plugin-redirect/package.json, plugins/tools/plugin-redirect/rollup.config.ts, plugins/tools/plugin-redirect/src/cli/index.ts, pnpm-lock.yaml, tools/create-vuepress/package.json, tools/create-vuepress/rollup.config.ts, tools/create-vuepress/src/action.ts, tools/create-vuepress/src/index.ts, tools/vp-update/package.json, tools/vp-update/rollup.config.ts, tools/vp-update/src/index.ts
cac is no longer actively maintained, so we are switching to commander.
=> feat: replace cac with commander

docs/plugins/blog/blog/guide.md, docs/zh/plugins/blog/blog/guide.md
`title`property is used in `TagList` or `StarList` components -  https://ecosystem.vuejs.press/plugins/blog/blog/guide.html#customizing-categories-and-types
It done similarly to an e2e example - https://github.com/vuepress/ecosystem/blob/main/e2e/docs/.vuepress/config.ts#L120
=> Update guide.md with missing title in getInfo option

docs/plugins/markdown/shiki.md, docs/zh/plugins/markdown/shiki.md, plugins/markdown/plugin-shiki/src/node/shikiPlugin.ts, plugins/markdown/plugin-shiki/src/node/utils.ts, tools/highlighter-helper/src/node/lineNumbers/options.ts, tools/highlighter-helper/src/node/lineNumbers/plugin.ts
=> feat: disable `line-numbers` within `twoslash` code block

plugins/markdown/plugin-markdown-hint/src/node/cleanMarkdownEnv.ts, plugins/markdown/plugin-markdown-hint/src/node/hint.ts
=> fix(plugin-markdown-hint): cleanup the `env` passed into `renderInline`

tools/helper/src/client/styles/transition/fade-in-down.scss, tools/helper/src/client/styles/transition/fade-in-height-expand.scss, tools/helper/src/client/styles/transition/fade-in-left.scss, tools/helper/src/client/styles/transition/fade-in-right.scss, tools/helper/src/client/styles/transition/fade-in-scale-up.scss, tools/helper/src/client/styles/transition/fade-in-up.scss, tools/helper/src/client/styles/transition/fade-in-width-expand.scss, tools/helper/src/client/styles/transition/fade-in.scss, tools/helper/src/client/styles/transition/slide-in-down.scss, tools/helper/src/client/styles/transition/slide-in-left.scss, tools/helper/src/client/styles/transition/slide-in-right.scss, tools/helper/src/client/styles/transition/slide-in-up.scss
I believe it is necessary to elevate the priority of transition properties.
Although doing so may cause layout flickering at the start and end of a transition when the element already has these configured transition properties.
However, when the priority of the same transition properties is too low, the transition animations cannot function properly.
I think we should prioritize ensuring that transition animations have a higher priority.
**Before**
**After**
=> feat(helper): add `!important` into transition properties

plugins/seo/plugin-sitemap/src/node/outputSitemap.ts
- Sitemap is always written to robots.txt
- If Sitemap does not exist in robots.txt, append the file to avoid overwriting
=> feat(plugin-sitemap): sitemap is always written to robots

docs/plugins/markdown/markdown-image.md, docs/zh/plugins/markdown/markdown-image.md, plugins/markdown/plugin-markdown-image/src/node/markdownImagePlugin.ts, plugins/markdown/plugin-markdown-image/src/node/options.ts
This PR allow setting `'strict'` with `size` and fixes some wrong documentation introduced by https://github.com/vuepress/ecosystem/pull/449. cc @LincZero
=> feat(plugin-markdown-image): allow 'strict' in size

docs/zh/plugins/markdown/revealjs/README.md, plugins/markdown/plugin-markdown-tab/src/client/styles/code-tabs.scss, plugins/markdown/plugin-markdown-tab/src/client/styles/tabs.scss, plugins/markdown/plugin-revealjs/src/client/styles/reveal-js.scss, themes/theme-default/src/client/components/VPPage.vue, themes/theme-default/src/client/styles/content/code.scss, tools/highlighter-helper/src/client/styles/base.scss, tools/highlighter-helper/src/client/styles/code-block-title.scss, tools/highlighter-helper/src/client/styles/notation-diff.scss, tools/highlighter-helper/src/client/styles/notation-highlight.scss
This PR unified all styles that are related to the default theme `1.5rem` padding in mobile view to theme default scope.
=> fix: fix code block related style

docs/.vuepress/styles/index.scss, docs/package.json, pnpm-lock.yaml, tools/highlighter-helper/package.json, tools/highlighter-helper/scss/code-title-icon.scss
E.g.:
```scss
@include code-title-icon.style(
(
title: ".vuepress/config.ts",
match: "equals",
icon: "https://theme-hope-assets.vuejs.press/logo.svg",
),
(
title: ".vuepress/client.ts",
match: "equals",
icon: "https://theme-hope-assets.vuejs.press/logo.svg",
),
(
title: ".vuepress/theme.ts",
match: "equals",
icon: "https://theme-hope-assets.vuejs.press/logo.svg",
),
(
title: ".scss",
match: "endsWith",
icon: "https://sass-lang.com/assets/img/logos/logo.svg",
),
(
title: ".md",
match: "endsWith",
icon: "https://theme-hope.vuejs.press/assets/image/markdown.svg",
),
(
title: ".vue",
match: "endsWith",
icon: "https://theme-hope.vuejs.press/assets/image/vue.svg",
)
);
```
=> feat(highlighter-helper): helper to inject icons for code-title-bar

tools/create-vuepress/template/blog/get-started.md, tools/create-vuepress/template/docs/get-started.md
This PR fixes a typo in `get-started.md` found in both the blog and docs templates by the `create-vuepress` tool.
=> fix(create-vuepress): fix typo in get-started.md

plugins/development/plugin-git/src/node/locales.ts
- [] Provide a description in this PR that addresses **what** the PR is solving. If this PR is going to solve an existing issue, please reference the issue (e.g. `close #123`).
remove colon from "lastUpdated" label in plugin-git
**Before**
https://assets.cumen.fun/upload/017cdaf1-c5fa-788e-eea2-d0ee249f902b/0197678a-e12e-d9de-8dc1-7f30d719ec02
https://assets.cumen.fun/upload/017cdaf1-c5fa-788e-eea2-d0ee249f902b/0197678a-e12e-c81a-8a6b-6e26efb5a1b7
**After**
https://assets.cumen.fun/upload/017cdaf1-c5fa-788e-eea2-d0ee249f902b/0197678a-e12e-8e7e-2134-86294284dd5d
=> fix(locale): remove colon from "latestUpdateAt" label in plugin-git

plugins/markdown/plugin-markdown-chart/src/client/components/Mermaid.ts
I believe there is no need to set built-in theme variables in `Mermaid`, as the default styles are already quite excellent.
These built-in theme settings hinder users from customizing their styles. 
Therefore, I think it is appropriate to remove them. 
Using `theme:dark` directly in dark mode is more reasonable.
=> feat(plugin-markdown-chart): remove mermaid theme default variables

plugins/markdown/plugin-markdown-chart/src/client/components/ChartJS.ts, themes/theme-default/src/client/composables/useDarkMode.ts, tools/helper/src/client/composables/useDarkMode.ts, tools/helper/tsconfig.build.json
Now, themes are required to import `darkmodeSymbol` from `@vuepress/helper` and provides darkmode variable in root setup function.
This avoids plugins that need darkmode status always being initialized with `darkmode: false` then a possible update.
=> feat(helper): improve darkmode

docs/.vuepress/configs/sidebar/en.ts, docs/.vuepress/configs/sidebar/zh.ts, docs/plugins/tools/replace-assets.md, docs/zh/plugins/tools/replace-assets.md, e2e/docs/.vuepress/config.ts, e2e/docs/replace-assets/README.md, e2e/package.json, e2e/tests/plugin-replace-assets/replace-assets.spec.ts, plugins/tools/plugin-replace-assets/package.json, plugins/tools/plugin-replace-assets/rollup.config.ts, plugins/tools/plugin-replace-assets/src/node/constants.ts, plugins/tools/plugin-replace-assets/src/node/index.ts, plugins/tools/plugin-replace-assets/src/node/normalizeRules.ts, plugins/tools/plugin-replace-assets/src/node/replaceAssetsPlugin.ts, plugins/tools/plugin-replace-assets/src/node/transformAssets.ts, plugins/tools/plugin-replace-assets/src/node/types.ts, plugins/tools/plugin-replace-assets/src/node/unplugin.ts, plugins/tools/plugin-replace-assets/src/node/utils.ts, plugins/tools/plugin-replace-assets/tests/__snapshots__/transformAssets.spec.ts.snap, plugins/tools/plugin-replace-assets/tests/normalizeRules.spec.ts, plugins/tools/plugin-replace-assets/tests/transformAssets.spec.ts, plugins/tools/plugin-replace-assets/tests/utils.spec.ts, plugins/tools/plugin-replace-assets/tsconfig.build.json, pnpm-lock.yaml, tsconfig.build.json
```
export default {
plugin: [replaceAssetsPlugin('https://cdn.com')]
}
```
source:
```md
```
dist output:
```
```
=> feat: add `plugin-replace-assets`

plugins/markdown/plugin-shiki/src/node/markdown/highlightLinesPlugin.ts, plugins/markdown/plugin-shiki/src/node/markdown/index.ts, plugins/markdown/plugin-shiki/src/node/shikiPlugin.ts, plugins/markdown/plugin-shiki/src/node/utils.ts, plugins/markdown/plugin-shiki/tests/__snapshots__/shiki-preWrapper.spec.ts.snap, plugins/markdown/plugin-shiki/tests/shiki-preWrapper.spec.ts
close #555
**Before**
**After**
=> fix(plugin-shiki): fix incorrect highlight lines parsing, close #555
