vuepress/ecosystem

docs/plugins/baidu-analytics.md, docs/zh/plugins/baidu-analytics.md
improve baidu analytics docs about spa mode
=> docs(plugin-baidu-analytics): improve baidu analytics docs about SPA mode

plugins/plugin-copy-code/src/client/styles/copy-code.css, plugins/plugin-copy-code/src/client/styles/copy-code.scss
=> fix(plugin-copy-code): copy button render incorrectly in Safari

plugins/plugin-prismjs/src/node/markdown/highlightPlugin.ts, plugins/plugin-prismjs/tests/__snapshots__/prismjs-preWrapper.spec.ts.snap
```diff
- <pre class="language-typescript">
+ <pre class="prismjs language-typescript">
```
=> feat(plugin-prismjs): add `prismjs` classname to `<pre>`

docs/.vuepress/configs/navbar/en.ts, docs/.vuepress/configs/navbar/zh.ts
=> docs: add theme-plume into navbar

docs/plugins/markdown/shiki.md, docs/zh/plugins/markdown/shiki.md, plugins/markdown/plugin-shiki/package.json, plugins/markdown/plugin-shiki/src/node/markdown/applyHighlighter/index.ts, pnpm-lock.yaml
=> feat(plugin-shiki): rename `getHighlighter` to `createHighlighter`

docs/.vuepress/configs/navbar/en.ts, docs/.vuepress/configs/navbar/zh.ts
Add reco theme in ecosystem site.
**Before**
**After**
=> docs: add reco theme

themes/theme-default/src/client/styles/content/code-notation.scss
=> fix(theme-default): fix incorrect code notation diff layout, close #212

themes/theme-default/src/client/layouts/NotFound.vue
=> fix(theme-default): fix incorrect 404 page layout, close #207

docs/plugins/markdown/shiki.md, docs/zh/plugins/markdown/shiki.md, plugins/markdown/plugin-shiki/src/node/markdown/applyHighlighter/getLanguage.ts, plugins/markdown/plugin-shiki/src/node/markdown/applyHighlighter/index.ts
=> perf(plugin-shiki): improve logging when language is not available

plugins/features/plugin-copy-code/src/client/styles/copy-code.scss, plugins/markdown/plugin-shiki/src/client/styles/shiki.scss, themes/theme-default/src/client/components/global/CodeGroup.ts, themes/theme-default/src/client/styles/code-group.scss, themes/theme-default/src/client/styles/vars.scss, tools/highlighter-helper/src/client/styles/line-numbers.scss, tools/highlighter-helper/src/client/styles/notation-highlight.scss, tools/highlighter-helper/src/client/styles/notation-word-highlight.scss
=> fix: improve code highlight style, close #222, #223

plugins/markdown/plugin-markdown-math/src/node/prepare/prepareClientConfigFile.ts
=> fix(plugin-markdown-math): incorrect import css path

plugins/markdown/plugin-markdown-hint/src/node/hint.ts
Input:
````md
::: important Custom Title `code`
A important container with customized title.
:::
````
Output:
**Before**
**After**
=> feat(plugin-markdown-hint): add inline rendering support for title

docs/plugins/development/git.md, docs/zh/plugins/development/git.md, plugins/development/plugin-git/src/node/types.ts, plugins/development/plugin-git/src/node/utils/getCommits.ts, plugins/development/plugin-git/src/node/utils/resolveChangelog.ts, plugins/development/plugin-git/src/node/utils/resolveContributors.ts
The commit body may include co-author information:
``` txt
Co-authored-by: xxxx <xxxx@email.com>
Co-authored-by: xxxx <xxxx@email.com>
```
They should also be collected as contributors and changlog.
=> feat(plugin-git): add collect of co-authors

plugins/development/plugin-git/src/node/resolveContributors.ts
Since the `commits` information is sorted starting from the latest, this means that the first contributor obtained from the `commits` may not necessarily be the original `contributor` of the file.
=> feat(plugin-git): improve contributors sorting

tools/create-vuepress/src/utils/getRegistry.ts
=> fix(create-vuepress): wrong registry command

docs/zh/plugins/markdown/markdown-include.md
=> docs: fix typos

plugins/markdown/plugin-markdown-hint/src/node/hint.ts
close #380
**Before**
**After**
=> fix(plugin-markdown-hint): fix missing `env` in title inline rendering, close #380

docs/plugins/features/notice.md, docs/zh/plugins/features/notice.md, e2e/docs/.vuepress/config.ts, e2e/docs/.vuepress/notice.md, e2e/docs/notice/file.md, e2e/tests/plugin-notice/notice.spec.ts, plugins/features/plugin-notice/package.json, plugins/features/plugin-notice/src/client/components/Notice.ts, plugins/features/plugin-notice/src/client/composables/index.ts, plugins/features/plugin-notice/src/client/composables/useNoticeOptions.ts, plugins/features/plugin-notice/src/client/config.ts, plugins/features/plugin-notice/src/client/index.ts, plugins/features/plugin-notice/src/client/noticeOptions.d.ts, plugins/features/plugin-notice/src/node/getNoticeOptions.ts, plugins/features/plugin-notice/src/node/noticePlugin.ts, plugins/features/plugin-notice/src/node/prepareNoticeOptions.ts, plugins/features/plugin-notice/src/shared/notice.ts, plugins/features/plugin-notice/tsconfig.build.json, pnpm-lock.yaml, tsconfig.json
close #376
**Before**
**After**
=> feat(plugin-notice): add markdown format support for notice content, close #376

plugins/markdown/plugin-markdown-hint/src/node/hint.ts
=> fix(plugin-markdown-hint): fix `env.title` being incorrectly overwritten in `renderInline`

docs/plugins/development/git.md, docs/zh/plugins/development/git.md, plugins/development/plugin-git/rollup.config.ts, plugins/development/plugin-git/src/client/composables/useGitLocales.ts, plugins/development/plugin-git/src/client/config.ts, plugins/development/plugin-git/src/node/gitPlugin.ts, plugins/development/plugin-git/src/node/prepareClientConfigFile.ts
close #389
**Before**
**After**
=> feat(plugin-git): export global component, close #389

docs/plugins/development/git.md, docs/zh/plugins/development/git.md, plugins/development/plugin-git/src/node/options.ts, plugins/development/plugin-git/src/node/resolveChangelog.ts, plugins/development/plugin-git/src/node/resolveContributors.ts, plugins/development/plugin-git/src/node/utils/getContributorInfo.ts
=> feat(plugin-git): add support to find git contributor by email

tools/helper/src/client/styles/transition/fade-in-down.scss, tools/helper/src/client/styles/transition/fade-in-height-expand.scss, tools/helper/src/client/styles/transition/fade-in-left.scss, tools/helper/src/client/styles/transition/fade-in-right.scss, tools/helper/src/client/styles/transition/fade-in-scale-up.scss, tools/helper/src/client/styles/transition/fade-in-up.scss, tools/helper/src/client/styles/transition/fade-in-width-expand.scss, tools/helper/src/client/styles/transition/slide-in-down.scss, tools/helper/src/client/styles/transition/slide-in-left.scss, tools/helper/src/client/styles/transition/slide-in-right.scss, tools/helper/src/client/styles/transition/slide-in-up.scss, tools/helper/src/client/styles/transition/vars.scss
=> feat(helper): add `!important` to transition

tools/helper/src/client/components/Transitions/FadeInExpandTransition.ts
=> fix(helper): conditionally apply `mode` prop in `FadeInExpandTransition`

docs/.vuepress/components/VPNavbarDropdown.vue, themes/theme-default/src/client/components/VPFadeSlideYTransition.vue, themes/theme-default/src/client/components/VPNavbarDropdown.vue
=> feat(theme-default): improve theme transition animation

tools/shiki-twoslash/src/node/createTwoslashTransformer.ts
=> fix(shiki-twoslash): fix typo error

docs/plugins/search/meilisearch.md, docs/zh/plugins/search/meilisearch.md
=> docs(plugin-meilisearch): improve docs

plugins/seo/plugin-seo/src/node/generateRobotsTxt.ts
- When used with plugin-sitemap, robots.txt will be overwritten
=> fix(plugin-seo): overlay issue when using with plugin-sitemap

plugins/seo/plugin-seo/src/node/generateRobotsTxt.ts
not add "\n" if the file does not exist
=> feat(plugin-seo): not add "\n" if the file does not exist

plugins/features/plugin-copy-code/src/client/composables/useCopyCode.ts
=> fix(plugin-copy-code): fix hydration mismatch

docs/.vuepress/configs/sidebar/en.ts, docs/.vuepress/configs/sidebar/zh.ts, docs/plugins/tools/auto-frontmatter.md, docs/zh/plugins/tools/auto-frontmatter.md, e2e/docs/.vuepress/config.ts, e2e/docs/auto-frontmatter/README.md, e2e/docs/auto-frontmatter/no-generate.md, e2e/package.json, e2e/tests/plugin-auto-frontmatter/auto-frontmatter.spec.ts, e2e/utils/source.ts, plugins/tools/plugin-auto-frontmatter/package.json, plugins/tools/plugin-auto-frontmatter/rollup.config.ts, plugins/tools/plugin-auto-frontmatter/src/node/autoFrontmatterPlugin.ts, plugins/tools/plugin-auto-frontmatter/src/node/createFilter.ts, plugins/tools/plugin-auto-frontmatter/src/node/generateFrontmatter.ts, plugins/tools/plugin-auto-frontmatter/src/node/helper/addCreateDate.ts, plugins/tools/plugin-auto-frontmatter/src/node/helper/addPermalink.ts, plugins/tools/plugin-auto-frontmatter/src/node/helper/addTitle.ts, plugins/tools/plugin-auto-frontmatter/src/node/helper/index.ts, plugins/tools/plugin-auto-frontmatter/src/node/index.ts, plugins/tools/plugin-auto-frontmatter/src/node/resolveRules.ts, plugins/tools/plugin-auto-frontmatter/src/node/types.ts, plugins/tools/plugin-auto-frontmatter/src/node/utils.ts, plugins/tools/plugin-auto-frontmatter/tsconfig.build.json, pnpm-lock.yaml, tsconfig.build.json
=> feat: add `plugin-auto-frontmatter`

plugins/markdown/plugin-markdown-chart/src/node/markdownChartPlugin.ts
fix error when using plantuml options.
Same here: 
https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/4640
https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/4641
**Before**
**After**
=> fix(plugin-markdown-chart): fix plantuml
